"""empty message

Revision ID: 1760b73dffa3
Revises: 70e50b2b8332
Create Date: 2016-03-22 11:31:44.502000

"""

# revision identifiers, used by Alembic.
revision = '1760b73dffa3'
down_revision = '70e50b2b8332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_colors', sa.String(), nullable=True))
    op.drop_column('users', 'favorite_color')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'favorite_colors')
    ### end Alembic commands ###
