"""empty message

Revision ID: 70e50b2b8332
Revises: 2a3142a0fee3
Create Date: 2016-03-22 11:02:24.527000

"""

# revision identifiers, used by Alembic.
revision = '70e50b2b8332'
down_revision = '2a3142a0fee3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_colors', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_colors')
    ### end Alembic commands ###
